OS_AUTH_URL: http://keystone-api.openstack.svc.cluster.local:80/v3
OS_PASSWORD: password
OS_PROJECT_NAME: service
OS_USERNAME: nova
OS_USER_DOMAIN_NAME: default
OS_REGION_NAME: RegionOne
TIMEOUT_SECONDS: 20
OS_POLLING_INTERVAL: 60
OS_RETRIES: 1
LISTEN_PORT: 19103
OS_CPU_OC_RATIO: 1.5
OS_RAM_OC_RATIO: 1